### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MenTNT** [JoseHenriqueSiqueira/WhatsaAppChatBot_OpenaiChatGPT_Python#1]
Sincronizando Mensagens...
Mensagens Sincronizadas
Traceback (most recent call last):
  File "WhatsappBot.py", line 62, in <module>
    WhatsappBot.run()
  File "WhatsappBot.py", line 38, in run
    last_parent = divs[-1] # Obtendo o div mais recente
IndexError: list index out of range

**Comment by JoseHenriqueSiqueira** [comment]
That's a problem I forgot to solve. I will update the repository today. Basically this error happens when the user has no message.

**Comment by JoseHenriqueSiqueira** [comment]
I added a check for this error not to happen. Basically now it will be analyzing if the user sent any messages. If he doesn't have it, the script will be running waiting for a message.
